---
title: "Data Description"
output: html_document
date: "2023-06-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

boston <- read_csv("data/boston_marathon_2023.csv")
boston_marathon_men_2023 <- read_csv("data/boston_marathon_men_2023.csv")
```

# Description
This data was scraped from the Boston Athletic Association website that has all results from each Boston Marathon. The `boston_marathon_2023.csv` dataset contains 26598 total observations of all the male and female runners of the 2023 race with each row representing a different runner.
The `boston_marathon_men_2023.csv` data set contains 15175 observations.
The `boston_marathon_women_2023.csv` data set contains 11423 observations. 

| Variable | Description |
|----|-------------|
| age_group | age group of the runner |
| place_overall | finishing place of the runner out of all runners |
| place_gender | finishing place of runner among the same gender |
| place_division | finishing place of runner among runners of the same gender and age group |
| name | name of runner |
| gender | gender of runner |
| team | team the runner is affiliated with |
| bib_number | bib number of runner |
| half_time | half marathon time of runner |
| finish_net | finishing time timed from when they cross the starting gate |
| finish_gun | finishing time of runner timed from when the starter gun is fired |
| age_group | age group of the runner |
| half_time_sec | half marathon time in seconds |
| finish_net_sec | net finish in seconds |
| finish_gun_sec | gun finish in seconds 

# References 

https://results.baa.org/2023/?pid=start&pidp=start



