---
title: "ufc"
output: html_document
date: "2023-07-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Scraping and Cleaning
```{r}
url <- "http://ufcstats.com/statistics/fighters?char=a&page=all"
objs <- read_html(url)%>%
      html_nodes("table")%>%
      html_table()

ufc <- objs[[1]]

ufc <- ufc%>%
  separate(`Ht.`, into = c("feet", "inches"), sep = "\'")%>%
  mutate(feet = parse_number(feet),
         inches = parse_number(inches))

write_csv(x = ufc, file = "ufc.csv")

ufc <- read_csv("ufc.csv", na = c("","NA","--"))

ufc<- ufc%>%
  mutate(height_inches = feet*12+inches,
         weight_lbs = parse_number(`Wt.`),
         reach_inches = parse_number(Reach))%>%
  select(-4, -5, -6, -7, -12 )%>%
  slice(-1)

write_csv(x = ufc, file = "ufc.csv")
ufc <- read_csv("ufc.csv")
```

# Analyzing 

-ANOVA with stance and wins
```{r}
winaov = aov(W ~ factor(Stance), data = ufc)
summary(winaov)
model.tables(winaov, type = "means")
model.tables(winaov, type = "effects")
```

