---
title: "boston_marathon_analysis"
output: html_document
date: "2023-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
bostonMen <- read_csv("data/boston_marathon_men_2023.csv")
bostonWomen <- read_csv("data/boston_marathon_women_2023.csv")

bostonMen<- bostonMen%>%
  mutate(age_group = factor(age_group))

bostonWomen<- bostonWomen%>%
  mutate(age_group = factor(age_group))
```
# 18-39
```{r}
men_18_39 <- lm(finish_net_sec ~ age_group, data = bostonMen)
newx = data.frame(age_group = "18-39")
predict(men_18_39, newdata = newx, interval = "conf", level = 0.90) # dif = 108.11

women_18_39 <- lm(finish_net_sec ~ age_group, data = bostonWomen)
newx = data.frame(age_group = "18-39")
predict(women_18_39, newdata = newx, interval = "conf", level = 0.90) # dif = 108.63

# .52 in difference between men and women
```
# 40-44
```{r}
men_40_44 <- lm(finish_net_sec ~ age_group, data = bostonMen)
newx = data.frame(age_group = "40-44")
predict(men_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 166.02

women_40_44 <- lm(finish_net_sec ~ age_group, data = bostonWomen)
newx = data.frame(age_group = "40-44")
predict(women_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 175.19 
# 9.17 in difference between men and women
```
# 45-49
```{r}
men_45_49 <- lm(finish_net_sec ~ age_group, data = bostonMen)
newx = data.frame(age_group = "45-49")
predict(men_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 165.6

women_45_49 <- lm(finish_net_sec ~ age_group, data = bostonWomen)
newx = data.frame(age_group = "45-49")
predict(women_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 178.11

# 12.51 difference between men and women
```
# 50-54
```{r}
men_50_54 <- lm(finish_net_sec ~ age_group, data = bostonMen)
newx = data.frame(age_group = "50-54")
predict(men_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 173.49

women_50_54 <- lm(finish_net_sec ~ age_group, data = bostonWomen)
newx = data.frame(age_group = "50-54")
predict(women_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 218.52

# 45.03 difference between men and women
```
# 55-59
```{r}
men_55_59 <- lm(finish_net_sec ~ age_group, data = bostonMen)
newx = data.frame(age_group = "55-59")
predict(men_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 208.41

women_55_59 <- lm(finish_net_sec ~ age_group, data = bostonWomen)
newx = data.frame(age_group = "55-59")
predict(women_40_44, newdata = newx, interval = "conf", level = 0.90) # dif = 265.93

# 57.52 difference between men and women
```
# Conclusions so far 
As age group increases, the spread of the confidence intervals increases consistently more for women than for men. Each time we increase by age group, the gap becomes larger and larger.