---
title: "Boston Marathon 2023"
output: html_document
date: "2023-06-13"
---


# 11423 total female runners
# 15175 total male runners
# excluded from the total are non-binary, wheelchair, handcycles, and duo teams
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# All Women's Results
```{r}


library(rvest)
library(tidyverse)
library(lubridate)


boston_marathon_1_page <- function(i, sex = c("W","M")){
  
  base_url <- "https://results.baa.org/2023/?page="
  middle_url <- "&event=R&event_main_group=runner&num_results=1000&pid=list&pidp=start&search%5Bsex%5D="
  end_url <- "&search%5Bage_class%5D=%25"
  
  url <- paste0(base_url, i, middle_url, sex, end_url)
  
  obs <- read_html(url) |> 
    html_nodes("li.list-group-item")
  
  tmp <- obs |> html_text(trim = TRUE)
  X <- tmp[-(1:2)] |> str_split(pattern = "(\n)+", simplify = TRUE)

  return(X)
}


boston_marathon_women <- boston_marathon_1_page(i = 1, sex = "W")

boston_marathon_women<-
  boston_marathon_women%>%
  as.data.frame()%>%
  rename(place_overall = V1, place_gender = V2, place_division = V3, 
         name = V4, team = V7, bib = V8, half_time = V11, finish_net = V12, 
         finish_gun = V13)%>%
  mutate(sex = ("W"),
         across(c(1,2,3), ~ parse_number(.)))%>%
  separate(col = bib, into = c("rem","bib"), sep = 5)%>%
  separate(col = half_time, into = c("no","half_time"), sep = "F" )%>%
  separate(col = finish_net, into = c("remove","finish_net"), sep = "t")%>%
  separate(col = finish_gun, into = c("empty","finish_gun"), sep = 12 )%>%
    select(1,2,3,4,9,13,15,17,18)%>%
    mutate(half_time = hms(half_time),
           finish_net = hms(finish_net),
           finish_gun = hms(finish_gun))

         
for(i in 2:12){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "W")

additional_rows<- additional_rows%>%
    as.data.frame()%>%
  rename(place_overall = V1, place_gender = V2, place_division = V3, 
         name = V4, team = V7, bib = V8, half_time = V11, finish_net = V12, 
         finish_gun = V13)%>%
  mutate(sex = ("W"),
         across(c(1,2,3), ~ parse_number(.)))%>%
  separate(col = bib, into = c("rem","bib"), sep = 5)%>%
  separate(col = half_time, into = c("no","half_time"), sep = "F" )%>%
  separate(col = finish_net, into = c("remove","finish_net"), sep = "t")%>%
  separate(col = finish_gun, into = c("empty","finish_gun"), sep = 12 )%>%
    select(1,2,3,4,9,13,15,17,18)%>%
    mutate(half_time = hms(half_time),
           finish_net = hms(finish_net),
           finish_gun = hms(finish_gun))

boston_marathon_women <- bind_rows(boston_marathon_women, additional_rows)
  
  
}
# within each run of the loop add Sys.sleep(rpois(1, 3)+1)


```
# All Men's Results
```{r}
boston_marathon_men <- boston_marathon_1_page(i = 1, sex = "M")

boston_marathon_men<-
  boston_marathon_men%>%
  as.data.frame()%>%
  rename(place_overall = V1, place_gender = V2, place_division = V3, 
         name = V4, team = V7, bib = V8, half_time = V11, finish_net = V12, 
         finish_gun = V13)%>%
  mutate(sex = ("M"),
         across(c(1,2,3), ~ parse_number(.)))%>%
  separate(col = bib, into = c("rem","bib"), sep = 5)%>%
  separate(col = half_time, into = c("no","half_time"), sep = "F" )%>%
  separate(col = finish_net, into = c("remove","finish_net"), sep = "t")%>%
  separate(col = finish_gun, into = c("empty","finish_gun"), sep = 12 )%>%
    select(1,2,3,4,9,13,15,17,18)%>%
    mutate(half_time = hms(half_time),
           finish_net = hms(finish_net),
           finish_gun = hms(finish_gun))

         
for(i in 2:16){
  Sys.sleep(rpois(1, 3)+1)
added_rows <- boston_marathon_1_page(i, sex = "M")

added_rows<- added_rows%>%
    as.data.frame()%>%
  rename(place_overall = V1, place_gender = V2, place_division = V3, 
         name = V4, team = V7, bib = V8, half_time = V11, finish_net = V12, 
         finish_gun = V13)%>%
  mutate(sex = ("M"),
         across(c(1,2,3), ~ parse_number(.)))%>%
  separate(col = bib, into = c("rem","bib"), sep = 5)%>%
  separate(col = half_time, into = c("no","half_time"), sep = "F" )%>%
  separate(col = finish_net, into = c("remove","finish_net"), sep = "t")%>%
  separate(col = finish_gun, into = c("empty","finish_gun"), sep = 12 )%>%
    select(1,2,3,4,9,13,15,17,18)%>%
    mutate(half_time = hms(half_time),
           finish_net = hms(finish_net),
           finish_gun = hms(finish_gun))

boston_marathon_men <- bind_rows(boston_marathon_men, added_rows)
}
```



```{r}
write_csv(x = boston_marathon_men, file = "data/boston_marathon_men_2023.csv")
write_csv(x = boston_marathon_women,
          file ="data/boston_marathon_women_2023.csv")
boston_marathon_2023 <- bind_rows(boston_marathon_men, boston_marathon_women)
write_csv(boston_marathon_2023,
          file = "data/boston_marathon_2023.csv")
```

