---
title: League of Legends
author: George Charalambous
date: May 23, 2023
description: x 
categories:
  - Dplyr
  - Joining functions
---
## Motivation

This data set examines the goals and shots in two prominent lacrosse leagues: the Premier Lacrosse League (PLL) and the National Lacrosse League (NLL). The PLL and NLL are highly regarded professional lacrosse leagues that feature top-tier athletes from around the world. The PLL is played in an indoor, smaller field while the NLL plays on an outdoor field with traditional dimensions. This data set allows for an analysis of goal-scoring within these leagues. 

## Data

The data set has 162 rows with 9 columns. Each row represents a single lacrosse
match either in the Premier Lacrosse League or the National Lacrosse League.

| Variable | Description |
|----|-------------|
| Name | Name of the softball player |
|  | Name of the team for each player |
| BA | Batting average |
| R | Number of runs scored |
| H | Number of hits |

: [LOL_patch_12.22.csv](../data/LOL_patch_12.22.csv)
: [LOL_patch_12.23.csv](../data/LOL_patch_12.23.csv)

## Questions

Performing calculations like standard deviations and t-tests can help us compare 
the two different lacrosse leagues. Using or creating variables like
`goals_per_game` or `goals_per_48` can help when seeing if there is any statistically
significant differences between leagues. 

## References

Statistics. D1Softball. (2019, October 24). <https://d1softball.com/statistics/> 
