---
title: "overwatch"
output: html_document
date: "2023-06-20"
---

```{r}
library(tidyverse)
library(rvest)
library(dplyr)


## provide the URL and name it something (in this case, url).
url <- "https://www.overbuff.com/heroes?platform=pc&gameMode=competitive&role=damage&timeWindow=3months"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables

tab <- h |> html_nodes("table")
```

```{r}
overwatch_damage <- tab[[1]] |> html_table()
```

```{r}
## provide the URL and name it something (in this case, url).
url <- "https://www.overbuff.com/heroes?platform=pc&gameMode=competitive&role=support&timeWindow=3months"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables

tab <- h |> html_nodes("table")
```

```{r}
overwatch_support <- tab[[1]] |> html_table()
```

```{r}
## provide the URL and name it something (in this case, url).
url <- "https://www.overbuff.com/heroes?platform=pc&gameMode=competitive&role=tank&timeWindow=3months"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables

tab <- h |> html_nodes("table")
```

```{r}
overwatch_tank <- tab[[1]] |> html_table()
```















