---
title: "Triathlon Data Correlation Module"
author: "SLU Crew"
format: html
---

The dataset `ironman1819.csv` contains data on female finishers of the Lake Placid Ironman Triathlon from 2002 to 2021. The motivation for this data analysis is to explore the relationships between swim times, bike times, and run times (in minutes) in order to gain insights into the performance patterns of the athletes. By analyzing these relationships, we can understand the interplay between different segments of the race and potentially identify areas of improvement for athletes.  For this activity, we will specifically focus on times from finishers in the years 2018 and 2019.

1.  Watch the [introductory video](https://www.youtube.com/watch?v=zYG2qdJRolM){target="_blank"} for the module.

2.  Open the dataset `ironman1819.csv`. As Sarah True mentioned, these data are from female finishers of the Lake Placid Ironman Triathlon from 2002 to 2021. We will be focused on the relationships between swim times, bike times and run times. Each of these times are in minutes.

3.  In words, how strong do you expect the relationships to be between each of these pairs of times?

4.  Make a histogram and describe the distribution for each of these times

    a.  Swim times
    b.  Bike times
    c.  Run times

5.  Graph the relationship between swim times and bike times. From this graph, is it appropriate to calculate the correlation from these data? If so, estimate the correlation from the graph, then calculate the correlation and compare it to your estimate. If not, briefly explain why not.

6.  Graph the relationship between bike times and run times. From this graph, is it appropriate to calculate the correlation from these data? If so, estimate the correlation from the graph, then calculate the correlation and compare it to your estimate. If not, briefly explain why not.

7.  Graph the relationship between swim times and run times. From this graph, is it appropriate to calculate the correlation from these data? If so, estimate the correlation from the graph, then calculate the correlation and compare it to your estimate. If not, briefly explain why not.

8.  Which relationship has the strongest correlation? Why might that be?

9.  These data are for finishers of the triathlon. How might these relationships be different for athletes that did not finish or were disqualified?

10. What do you think is the causal mechanism for these correlations?

11. What do these correlations suggest for athletes about what aspects of their race they may want to concentrate on?
