---
title: "Cross Country Data Description"
author: visual
date: 06/23/2023
description: The data set looks at Men's 15 km cross-country ski results from the 2010, 2014, 2018, and 2022 Winter Olympics.
categories: 
- Density plots
- Side-by-Side Boxplots
- z-scores
---

## Motivation

It is widely thought that Scandinavian athletes are dominant in the sport of cross-country skiing. The motivation for this data analysis is to assess cross-country ski results (in minutes) in a variety of ways to compare the difference in performance of Scandinavian athletes in relation to the rest of the field. By choosing the correct response variable(s), we can better examine the true disparity in results among the athletes over the course of the last four Olympics.

## Data

The data set has 393 rows with 7 columns. Each row represents a Male competitor in the 15km cross-country ski event in the last four Winter olympics (2010, 2014, 2018, 2022).

\| Variable \| Description \|

\|\-\-\--\|\-\-\-\-\-\-\-\-\-\-\-\--\|

\| Rank \| The place the athlete finished in the event \|

\| Name \| The athlete's name \|

\| Country \| What country the athlete is from \|

\| Time_min \| The total time it took the athlete to complete the event (in minutes \|

\| Year \| The year of the event \|

\| scandinavian \| whether or not the athlete is from a Scandinavian country ( 1 = yes, 0 = no) \|

\| z-score \| The number of standard deviations the athlete's time is from the mean time of the particular event \|

:   \[mens_cc_ski_2010-22.csv\](../data/mens_cc_ski_2010-22.csv)

## Questions

Do Scandinavian cross-country skiers perform better than the field on average and has this phenomenon changed over time? What is the best method of of assessing and comparing results of these athletes for multiple years of these events?

## References

OlympianDatabase-Facts about the Olympics-Sportsencyclo

\<https://www.olympiandatabase.com/index.php?id=417&L=1\>
