---
title: "Merging Data"
output: html_document
date: "2023-07-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
aces <- read_csv("aces.csv", col_select = 1:2)
assists <- read_csv("assists.csv", col_select = 1:2)
attacks <- read_csv("attacks.csv", col_select = 1:2)
blocks <- read_csv("blocks.csv", col_select = 1:2)
digs <- read_csv("digs.csv", col_select = 1:2)
hitting <- read_csv("hitting_pctg.csv", col_select = 1:2)
kills <- read_csv("kills.csv", col_select = 1:2)
opp_hitting <- read_csv("opp_hitting.csv", col_select = 1:2)
service <- read_csv("service_aces.csv", col_select = 1:2)
win_loss <- read_csv("win_loss.csv")
```

```{r}
volleyball_2022_23 <- left_join(aces,assists, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, attacks, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, blocks, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, digs, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, hitting, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, kills, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, opp_hitting, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, service, by = "Team")
volleyball_2022_23 <- left_join(volleyball_2022_23, win_loss, by = "Team")
```

```{r}
volleyball_2022_23 <- 
  volleyball_2022_23%>%
  separate(Team, into = c("Team","Conference"), sep = "\\(", extra = "merge")%>%
  mutate(Conference = str_remove_all(Conference,"\\)"),
         Team = str_trim(Team))
```

```{r}
region <- read_csv("ncaa_vb_2022_2023.csv", col_select = 1:2)
region<-region%>%
  mutate(team = str_trim(team))



volleyball_2022_23 <- left_join(volleyball_2022_23, region, by = c("Team"="team"))
```

# separate team names in volleyball_2022_23 and join in region 
```{r}
write_csv(x = volleyball_2022_23, file = "volleyball_2022_23.csv")
vb <- vb%>%
  select(-service_aces)
write_csv(x = vb, file = "volleyball_2022_23.csv")

```

