---
title: "Olympics Database"
---

Here is an outline for how to acquire and clean data from https://www.olympiandatabase.com/

1. Go to Olympian Database: https://www.olympiandatabase.com/

Click on the "Results" tab and load
i) The Olympics of choice
ii) The Sport
iii) The Event

e.g., 
Beijing 2022 > Alpine Skiing > Women's Giant Salom

You should see a table with the event's results

2. Getting the Data into a CSV file

a. Copy/paste the table into Excel. However, you'll want to paste by right-clicking (Windows) or control-click (Mac) and the use the Paste Option of Matching Destination Style. (This will help get rid of a bunch of extra garbage that would otherwise be pasted along with the data.)

b. Add the 1, 2, 3 numbers to the ranking column

c. sort by this column to dump the blanks rows to the end

d. delete blank columns

e. Insert a row and add appropriate heading names (Rank, Name, Country, Time)

f. Save it as a CSV file. Be sure to give it a name using a similar structure to what I have in the data folder.

3. Load it in to R and finish cleaning it.

```{r}
wgs <- readr::read_csv("olympics_database/data/giant_salom_giant-salom_women_beijing2022.csv")
```


a. You'll need to drop NA rows (on the Rank column)
b. Convert the Time column into something useable. To do so,
  * replace the . with :
  * replace the , with .
  * use lubridate to convert this into a time object and finally turn it into a seconds column.
c. Save this cleaned file. Replace the original with this copy. (i.e., the write_csv statement will use the same filename as the read_csv statement)


Possible Questions:
Most of these data will have a similar structure, so many of the modules are likley to cover similar topics. 

If using just the one sport/file, things like

a. Univariate summary statistics and graphics are good
b. Outlier detection and/or z-scores
c. Analyzing the time differentials in the rankings.

You can also use more than one event and do some comparative analyses.

e.g., Compare Women's Giant Salom to the other events (Downhill, Super-G, Salom, and Giant Salom) using ANOVA or picking just two and using t-test.

** NOTE ON INFERENCE **
Since inference with data like this is sometimes a bit tricky, be sure to always include questions that have students think through what assumptions they are making about the data (in particular the "random sample" idea) and have them answer things related to the limitations of the analysis.



  
  