---
title: "NRL Players"
output: html_document
date: "2023-07-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Function
```{r}
rugby_function <- function(i){
  
  base_url <- "https://www.foxsports.com.au/nrl/nrl-premiership/stats/players?editiondata=none&fromakamai=true&pt=none&device=DESKTOP&wpa=BB44D82C3D7223D393F2AE47579FB5EA6791ABE4&pageNumber="
  
  
  
  
  url <- paste0(base_url, i)
  
  tryCatch({
    objs <- read_html(url)%>%
      html_nodes("table")%>%
      html_table()
    
    X <- objs[[8]]
    
    return(X)
  }, error = function(e) {
    message(paste("Error occurred for page", i, "- Skipping..."))
    return(NULL)
  })
}
```

```{r}
rugby_players <- rugby_function(i = 1)

for(i in 2:24){
  Sys.sleep(rpois(1, 3)+1)
  additional_rows <- rugby_function(i)
  
  tryCatch({
    rugby_players <- rbind(rugby_players, additional_rows)
  }, error = function(e) {
    message(paste("Error occurred while binding rows for page", i, "- Skipping..."))
  })
}
```


```{r}
write_csv(x = rugby_players, file = "rugby_players.csv")
nrl <- read_csv("rugby_players.csv", na = c("","NA","-"))
```



